# repo-a/mkdocs.yml
INHERIT: docs/_core/core.mkdocs.yml

# region Site
site_name: G4X-viewer
site_url: https://docs.singulargenomics.com/G4X-viewer/
site_description: Singular Genomics G4X-viewer documentation site

repo_name: G4X-viewer
repo_url: https://github.com/Singular-Genomics/G4X-viewer

# region Nav
nav:
  - Home: index.md
